{% set data = load_setup_py_data() %}

package:
  name: polylx
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/ondrolexa/polylx.git
  git_rev: {{ data.get('version') }}

build:
  noarch: python
  entry_points:
    - ipolylx=polylx.shell:main
  script: python setup.py install

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - matplotlib
    - shapely
    - pandas
    - networkx
    - scipy
    - pyshp

  run:
    - python
    - numpy
    - matplotlib
    - shapely
    - pandas
    - networkx
    - scipy
    - pyshp

test:
  # Python imports
  imports:
    - polylx
    - polylx.core
    - polylx.reports
    - polylx.utils
    - polylx.shell

about:
  home: https://github.com/ondrolexa/polylx.git
  license: BSD License
  summary: 'PolyLX - Python package to visualize and analyze microstructures'
  license_family: BSD
  doc_url: https://polylx.readthedocs.io
  dev_url: https://github.com/ondrolexa/polylx.git

extra:
  maintainers:
   - Ondrej Lexa <lexa.ondrej@gmail.com>
